apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: infra-poc-simple-rg
spec:
  forProvider:
    location: uksouth
  providerConfigRef:
    name: azure-pc

---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: infra-poc-simple
spec:
  forProvider:
    location: uksouth
    kubernetesVersion: '1.25.5'
    identity:
      - type: SystemAssigned
    defaultNodePool:
      - name: main
        nodeCount: 1
        vmSize: Standard_B2s
    dnsPrefix: dt
    resourceGroupNameRef:
      name: infra-poc-simple-rg
  providerConfigRef:
    name: azure-pc
